### ISSUE TITLE
jeu.jouer() planification

### ISSUE THREAD

**Issue by gustavogois** [gustavogois/gfi_josedias_sujetaventurier#4]
Prévoyez de mettre en œuvre cette méthode, qui correspond à la méthode principale du jeu. Réfléchissez, en termes généraux, à la manière dont la méthode doit être implémentée, aux opérations qui seront nécessaires, aux classes dans lesquelles ces opérations devraient être, etc.

**Comment by jcsilvamayor** [comment]
# Planification

## 1. Charger le jeu (classe **Jeu**)

- Charger le map (classe **MapJeu**)
- Charger le joueur (classe **Joueur**)
- Charger le chemin à suivre et charger les cordonées initiales (classe **Chemin**)

## 2. Faire le joueur suivre le chemin, en utilisant l'énuméré **Direction**.
- pendant le trajet, vérifier si la position suivante est valide ou non (si leas cordonnées sont d'une position valide ou si appartiennent au map).

**Comment by gustavogois** [comment]
Très bien @jcsilvamayor :-)
